# Use the official Python base image
FROM python:3.10

# Set the working directory
WORKDIR /byfinder

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app's source code
COPY . .

# Set environment variables (if needed)
ENV MONGO_HOST=localhost
ENV MONGO_PORT=3000

# Command to start the FastAPI server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
